#cloud-config
autoinstall:
  version: 1
  updates: all

  refresh-installer:
    update: true

  locale: en_US.UTF-8
  timezone: Asia/Tokyo

  keyboard:
    layout: jp
    variant: ""

  storage:
    layout:
      name: lvm
      sizing-policy: all
      encrypt: false
      # password: "CHANGE_ME_LUKS_PASSPHRASE" # change with plain password

  identity:
    realname: "eggplants"
    username: "eggplants"
    hostname: "eggplants-ThinkPad-X1-Carbon-Gen-9"
    password: "$6$0PAm9I8jVAUMHgAf$2SM/58YNb2eeN8UyQDnDCfyPoa1athwp3q./ZHKPAJPaTl/o4rSBW2TOz2v6dv/6AvwxI797krJwxXQMMqfl2/"

  ssh:
    install-server: false
    allow-pw: false

  early-commands:
    - apt-get update -y

  apt:
    preserve_sources_list: false
    mirror-selection:
      primary:
        - country-mirror
        - uri: "http://jp.archive.ubuntu.com/ubuntu"
        - uri: "http://archive.ubuntu.com/ubuntu"
    geoip: true
    fallback: abort


  shutdown: reboot
  late-commands:
    - curtin in-target -- apt-get update -y
    - curtin in-target -- apt-get install -y                                
        alsa-utils build-essential curl fonts-noto-cjk git gnupg2
        ibus-mozc language-pack-ja language-pack-ja-base                    
        network-manager-l2tp network-manager-l2tp-gnome                     
        pass pinentry-tty pkg-config uidmap zip unzip zsh
    - curtin in-target -- install -m 0755 -d /etc/apt/keyrings
    - curtin in-target -- chsh -s /usr/bin/zsh eggplants
    - |
      # Install Qfinder Pro
      curtin in-target -- bash -c 'curl -s '\''https://eu1.qnap.com/Liveupdate/SoftwareRelease.xml'\'' | grep -oEm1 '\''http://[^"]+/QNAPQfinderProUbuntux64[^"]+\.deb'\'' | xargs curl -Lo /tmp/qfinder.deb'
      curtin in-target -- apt-get install -y /tmp/qfinder.deb
      curtin in-target -- rm -f /tmp/qfinder.deb
    - curtin in-target -- su - eggplants -c 'git clone https://github.com/eggplants/setup-ubuntu.sh /home/eggplants/.config/home-manager'
    - curtin in-target -- apt-get autoremove -y
    - curtin in-target -- apt-get autoclean -y        
